name: Build, Push & Deploy

on:
  push:
    branches: [ main, Dev ]

jobs:
  build-linux:
    name: Build for Linux VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-jar
          path: target/*.jar

  build-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/tasklist-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tasklist-app:latest

  deploy-linux:
    name: Deploy to Linux VM
    runs-on: ubuntu-latest
    needs: build-linux 

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-jar
          path: ./artifact

      - name: Copy JAR to VM via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "./artifact/*.jar"
          target: "/home/${{ secrets.VM_USER }}/app"

      - name: Restart App on VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VM_USER }}/app
            pkill -f 'tasklist-0.0.1-SNAPSHOT.jar' || true
            nohup java -jar tasklist-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
